---

- name: Create directory to store configuration files
  file:
    path: "{{ renovate_dir }}"
    owner: root
    group: docker
    mode: 0775
    state: directory
    recurse: yes

- name: Create configuration files
  template:
    src: "{{ item }}.j2"
    dest: "{{ renovate_dir }}/{{ item | basename }}"
    owner: root
    group: docker
    mode: 0664
  with_items:
  - srv/docker/renovate/docker-compose.yml
  - srv/docker/renovate/config.json

- name: Create systemd unit files
  template:
    src: "{{ item }}.j2"
    dest: "{{ renovate_systemd_dir }}/{{ item | basename }}"
  with_items:
  - etc/systemd/system/renovate.service
  - etc/systemd/system/renovate.timer
  notify:
  - enable renovate
